### ISSUE TITLE
Apparent conflict affects h1, h2, etc. buttons

### ISSUE THREAD

**Issue by RationalRabbit** [crpietschmann/jHtmlArea#2]
There is a 2-year-old issue posted on CodePlex that states this is a Bootstrap conflict. Seems it is still a problem. Confirmed that this is a Bootstrap CSS conflict.
Both programs have classes of h1 through h6. For my usage, I was able to delete those classes in bootstrap.min.css without any problem.
![image](https://user-images.githubusercontent.com/32299865/30861068-6a0e295e-a27e-11e7-8d18-172813a5290d.png)

**Comment by patm87** [comment]
I just try this tool and I had the same issue

**Comment by DonnOMalley** [comment]
I've created a push request that should resolve this but in the meantime, you can fix this yourself with a little css in the jHtmlArea.css file

Change lines 35-40 from:
div.jHtmlArea .ToolBar ul li a.h1 { background-position: 0 -16px; }
div.jHtmlArea .ToolBar ul li a.h2 { background-position: -16px -16px; }
div.jHtmlArea .ToolBar ul li a.h3 { background-position: -32px -16px; }
div.jHtmlArea .ToolBar ul li a.h4 { background-position: -48px -16px; }
div.jHtmlArea .ToolBar ul li a.h5 { background-position: -64px -16px; }
div.jHtmlArea .ToolBar ul li a.h6 { background-position: -80px -16px; }

To:
div.jHtmlArea .ToolBar ul li a.h1 { background-position: 0 -16px; margin-top: 0px !important; margin-bottom: 0px !important; }
div.jHtmlArea .ToolBar ul li a.h2 { background-position: -16px -16px; margin-top: 0px !important; margin-bottom: 0px !important; }
div.jHtmlArea .ToolBar ul li a.h3 { background-position: -32px -16px; margin-top: 0px !important; margin-bottom: 0px !important; }
div.jHtmlArea .ToolBar ul li a.h4 { background-position: -48px -16px; margin-top: 0px !important; margin-bottom: 0px !important; }
div.jHtmlArea .ToolBar ul li a.h5 { background-position: -64px -16px; margin-top: 0px !important; margin-bottom: 0px !important; }
div.jHtmlArea .ToolBar ul li a.h6 { background-position: -80px -16px; margin-top: 0px !important; margin-bottom: 0px !important; }

**Comment by crpietschmann** [comment]
Thanks for the PR and the discussion of identifying the fix. It's been implemented in the repo. Not in the nuget package yet though.
